#lang racket

(require "AsipMain.rkt")

(define (3p4)
  (open-asip)
  (printf "~%")
  (enableCounters 100)
  (setMotors -150 150)
  (sleep 0.5)
  (stopMotors)
  (sleep 1)
  (printf "~a ~%"(getCount 0))
  (printf "~a ~%"(getCount 1))
  (setMotors 150 -150)
  (sleep 0.5)
  (stopMotors)
  (printf "~a ~%"(getCount 0))
  (printf "~a ~%"(getCount 1))
  (sleep 1)
  (setMotor 1 150)
  (sleep 0.5)
  (stopMotors)
  (sleep 1)
  (printf "~a ~%"(getCount 0))
  (printf "~a ~%"(getCount 1))
  (setMotor 1 -150)
  (sleep 0.5)
  (stopMotors)
  (printf "~a ~%"(getCount 0))
  (printf "~a ~%"(getCount 1))
  (close-asip)
  )